// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview A flow to optimize driver alerts based on urgency and information type.
 *
 * - optimizeDriverAlert - A function that handles the optimization of driver alerts.
 * - DriverAlertInput - The input type for the optimizeDriverAlert function.
 * - DriverAlertOutput - The return type for the optimizeDriverAlert function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const DriverAlertInputSchema = z.object({
  updateType: z
    .string()
    .describe(
      'The type of update being sent to the driver (e.g., passenger load prediction, incident report, schedule change)'
    ),
  urgencyLevel: z
    .string()
    .describe(
      'The urgency level of the update (e.g., low, medium, high, critical)'
    ),
  information: z.string().describe('The detailed information for the update.'),
});
export type DriverAlertInput = z.infer<typeof DriverAlertInputSchema>;

const DriverAlertOutputSchema = z.object({
  communicationMedium: z
    .string()
    .describe(
      'The recommended communication medium for the alert (e.g., chat, voice, notification)'
    ),
  alertMessage: z.string().describe('The formatted alert message for the driver.'),
});
export type DriverAlertOutput = z.infer<typeof DriverAlertOutputSchema>;

export async function optimizeDriverAlert(
  input: DriverAlertInput
): Promise<DriverAlertOutput> {
  return optimizeDriverAlertFlow(input);
}

const prompt = ai.definePrompt({
  name: 'driverAlertOptimizationPrompt',
  input: {schema: DriverAlertInputSchema},
  output: {schema: DriverAlertOutputSchema},
  prompt: `You are an AI assistant designed to optimize communication with bus drivers.
  Given the update type, urgency level, and information, determine the most effective communication medium (chat, voice, notification) and format an appropriate alert message for the driver.

  Update Type: {{{updateType}}}
  Urgency Level: {{{urgencyLevel}}}
  Information: {{{information}}}

  Consider the following:
  - Use voice for critical, time-sensitive information and incidents.
  - Use chat for non-critical schedule changes or minor updates.
  - Use notification for general information or reminders.

  Response:
  Communication Medium: {{communicationMedium}}
  Alert Message: {{alertMessage}}`,
});

const optimizeDriverAlertFlow = ai.defineFlow(
  {
    name: 'optimizeDriverAlertFlow',
    inputSchema: DriverAlertInputSchema,
    outputSchema: DriverAlertOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
